name: hex-app

services:
  psql:
    build: ./docker/postgres
    restart: always
    shm_size: 256mb
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    volumes:
      - psql_volume:/var/lib/postgresql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  psql_volume:

networks:
  app-network:
    driver: bridge
