// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: arithmatic_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArithmaticService_GetAdd_FullMethodName = "/pb.ArithmaticService/GetAdd"
	ArithmaticService_GetSub_FullMethodName = "/pb.ArithmaticService/GetSub"
	ArithmaticService_GetMul_FullMethodName = "/pb.ArithmaticService/GetMul"
	ArithmaticService_GetDiv_FullMethodName = "/pb.ArithmaticService/GetDiv"
)

// ArithmaticServiceClient is the client API for ArithmaticService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArithmaticServiceClient interface {
	GetAdd(ctx context.Context, in *OperationParametars, opts ...grpc.CallOption) (*Answer, error)
	GetSub(ctx context.Context, in *OperationParametars, opts ...grpc.CallOption) (*Answer, error)
	GetMul(ctx context.Context, in *OperationParametars, opts ...grpc.CallOption) (*Answer, error)
	GetDiv(ctx context.Context, in *OperationParametars, opts ...grpc.CallOption) (*Answer, error)
}

type arithmaticServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArithmaticServiceClient(cc grpc.ClientConnInterface) ArithmaticServiceClient {
	return &arithmaticServiceClient{cc}
}

func (c *arithmaticServiceClient) GetAdd(ctx context.Context, in *OperationParametars, opts ...grpc.CallOption) (*Answer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Answer)
	err := c.cc.Invoke(ctx, ArithmaticService_GetAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithmaticServiceClient) GetSub(ctx context.Context, in *OperationParametars, opts ...grpc.CallOption) (*Answer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Answer)
	err := c.cc.Invoke(ctx, ArithmaticService_GetSub_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithmaticServiceClient) GetMul(ctx context.Context, in *OperationParametars, opts ...grpc.CallOption) (*Answer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Answer)
	err := c.cc.Invoke(ctx, ArithmaticService_GetMul_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *arithmaticServiceClient) GetDiv(ctx context.Context, in *OperationParametars, opts ...grpc.CallOption) (*Answer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Answer)
	err := c.cc.Invoke(ctx, ArithmaticService_GetDiv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArithmaticServiceServer is the server API for ArithmaticService service.
// All implementations must embed UnimplementedArithmaticServiceServer
// for forward compatibility.
type ArithmaticServiceServer interface {
	GetAdd(context.Context, *OperationParametars) (*Answer, error)
	GetSub(context.Context, *OperationParametars) (*Answer, error)
	GetMul(context.Context, *OperationParametars) (*Answer, error)
	GetDiv(context.Context, *OperationParametars) (*Answer, error)
	mustEmbedUnimplementedArithmaticServiceServer()
}

// UnimplementedArithmaticServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArithmaticServiceServer struct{}

func (UnimplementedArithmaticServiceServer) GetAdd(context.Context, *OperationParametars) (*Answer, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdd not implemented")
}
func (UnimplementedArithmaticServiceServer) GetSub(context.Context, *OperationParametars) (*Answer, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSub not implemented")
}
func (UnimplementedArithmaticServiceServer) GetMul(context.Context, *OperationParametars) (*Answer, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMul not implemented")
}
func (UnimplementedArithmaticServiceServer) GetDiv(context.Context, *OperationParametars) (*Answer, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDiv not implemented")
}
func (UnimplementedArithmaticServiceServer) mustEmbedUnimplementedArithmaticServiceServer() {}
func (UnimplementedArithmaticServiceServer) testEmbeddedByValue()                           {}

// UnsafeArithmaticServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArithmaticServiceServer will
// result in compilation errors.
type UnsafeArithmaticServiceServer interface {
	mustEmbedUnimplementedArithmaticServiceServer()
}

func RegisterArithmaticServiceServer(s grpc.ServiceRegistrar, srv ArithmaticServiceServer) {
	// If the following call panics, it indicates UnimplementedArithmaticServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArithmaticService_ServiceDesc, srv)
}

func _ArithmaticService_GetAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationParametars)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmaticServiceServer).GetAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArithmaticService_GetAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmaticServiceServer).GetAdd(ctx, req.(*OperationParametars))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArithmaticService_GetSub_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationParametars)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmaticServiceServer).GetSub(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArithmaticService_GetSub_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmaticServiceServer).GetSub(ctx, req.(*OperationParametars))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArithmaticService_GetMul_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationParametars)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmaticServiceServer).GetMul(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArithmaticService_GetMul_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmaticServiceServer).GetMul(ctx, req.(*OperationParametars))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArithmaticService_GetDiv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationParametars)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArithmaticServiceServer).GetDiv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArithmaticService_GetDiv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArithmaticServiceServer).GetDiv(ctx, req.(*OperationParametars))
	}
	return interceptor(ctx, in, info, handler)
}

// ArithmaticService_ServiceDesc is the grpc.ServiceDesc for ArithmaticService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArithmaticService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ArithmaticService",
	HandlerType: (*ArithmaticServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdd",
			Handler:    _ArithmaticService_GetAdd_Handler,
		},
		{
			MethodName: "GetSub",
			Handler:    _ArithmaticService_GetSub_Handler,
		},
		{
			MethodName: "GetMul",
			Handler:    _ArithmaticService_GetMul_Handler,
		},
		{
			MethodName: "GetDiv",
			Handler:    _ArithmaticService_GetDiv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "arithmatic_service.proto",
}
